name: Update Website Links on Release

on:
  workflow_call:

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: CanCLID/jyutping.net
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update URL in .env
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          for url in $(gh release view latest --json assets --jq '.assets[].browser_download_url'); do
            if [[ $url == *.exe ]]; then
              sed -i "s|^VITE_DOWNLOAD_URL_WINDOWS=.*|VITE_DOWNLOAD_URL_WINDOWS=$url|" .env
            elif [[ $url == *.pkg ]]; then
              sed -i "s|^VITE_DOWNLOAD_URL_MAC=.*|VITE_DOWNLOAD_URL_MAC=$url|" .env
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .env
          if [ -n "$(git status --porcelain)" ]; then  # Push to GitHub if contents changed
            git commit -m "Update Installer URLs"
            git push origin main
          fi
